[features]
resolution = true
skip-lint = false

rps_game = "8ohu3RobXyZ2DebyJjbs2co9YCG275FUsVckEcmDbCos"
duel = "EdZzUwKd1X2ZWjxLPpz1cpEzMF7RUZC43Pq64v1VcK5X"

[programs.localnet]
rps_game = "8ohu3RobXyZ2DebyJjbs2co9YCG275FUsVckEcmDbCos"
duel = "EdZzUwKd1X2ZWjxLPpz1cpEzMF7RUZC43Pq64v1VcK5X"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx tsx node_modules/.bin/_mocha --timeout 1000000 tests/auto-match.ts"
init-queue = "npx ts-node scripts/init-queue.ts"
check-queue = "npx ts-node scripts/check-queue-status.ts"
generate-tenant-authority = "npx ts-node scripts/generate-tenant-authority.ts"
