[features]
resolution = true
skip-lint = false

anchor_rock_paper_scissor = "ENUPVoY1BtRBkdY5TwNqbQmpeU2nrUdJvRkPRDRqUuMU"

[programs.localnet]
anchor_rock_paper_scissor = "xc7RtasEqM2YNaRSiFfiMGKrHM6EjbbcGLK4b2fzjhb"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/auto-match.ts"
